version: '3.3'
services:
  frontend:
    build:
      context: frontend
      args:
        - API_BASE_URL=${API_BASE_URL}
    container_name: mesto-frontend
    image: mesto/frontend
    restart: always
    networks:
      - react-express
    depends_on:
      - mongo
      - backend
    ports:
      - "80:80"

  backend:
    build:
      context: backend
    container_name: mesto-backend
    image: mesto/backend
    restart: always
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - BASE_URL=${BASE_URL}
    networks:
      - express-mongo
      - react-express
      - grafana-loki
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  mongo:
    restart: always
    image:  mongo:4.4-focal
    container_name: mesto-mongodb
    volumes:
      - mongodb:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

networks:
  express-mongo:
  react-express:
  grafana-loki:

volumes:
  mongodb: